### ISSUE TITLE
Fatal Exception: java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by drspaceboo** [segmentio/analytics-android#316] opened 2015-07-09 06:33 UTC
I've been seeing this crash climb our ranks of crashes for our app.
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@221501b8 rejected from com.segment.analytics.Analytics$AnalyticsExecutorService@21e07d50[Running, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 301]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:103)
       at com.segment.analytics.SegmentDispatcher.performFlush(SourceFile:251)
       at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SourceFile:395)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

We have the following dependancies in our Gradle:
```
//Segment
compile('com.segment.analytics.android:analytics-core:3.0.2@aar') {
    transitive = true
}
compile('com.segment.analytics.android:analytics-integration-amplitude:3.0.2@aar') {
    transitive = true
}
compile('com.segment.analytics.android:analytics-integration-appsflyer:3.0.2@aar')
```

I haven't seen anyone else report this issue. Is this a known problem?

**Comment by f2prateek** [comment] 2015-07-16 23:48
Weird, I ran the SDK in a simple loop and couldn't reproduce:

```java
for (int i = 0; i < 10000; i++) {
  Analytics.with(this).track("Test Event");
}
```

Can you try updating to the latest version (3.1.5)?

**Comment by kellyfj** [comment] 2015-08-07 13:46
Any update on this issue - we are experiencing it and want to be sure it is fixed before upgrading. Thanks!

**Comment by f2prateek** [comment] 2015-08-07 15:37
Do you have a stack trace you can share and a reproducible case? My simple test case didn't reproduce the issue.

You can pass a custom exectuor to the library, so you could try playin g around with a few different ones as well.

**Comment by holmari** [comment] 2015-08-09 13:08
Prateek, answering on behalf of Frank - we don't know when this happens exactly, we're only seeing this crash with real users through our crash reporting system. There's several hundred crashes in the past few days.

It seems likely that this error is not caused by too many events sent, but rather that the executor is shut down but it still tries to flush afterwards. Could you take a look whether that is indeed the case here?

**Comment by f2prateek** [comment] 2015-08-09 19:58
I see, are you calling `analytics.shutdown()` in your app and enqueuing events after?

**Comment by holmari** [comment] 2015-08-11 06:57
I don't think we call shutdown() anywhere - at least I can't see any calls to it in our code as far as I can tell. Are there any cases where the executor could be shut down otherwise, from inside segment code?

If shutdown() is called and tracking is attempted afterwards, shouldn't track() or similar methods fail immediately, to pinpoint the code that posts events after shutdown? It might also make sense to allow the user of the library to define a policy - strict or ignore; in the former case, post-shutdown events would crash, while in the latter, the events would be simply ignored. Both seems like valid approaches to me.

**Comment by drspaceboo** [comment] 2015-08-11 07:53
@kellyfj,
Sorry we haven't yet tried upgrading to 3.1.5, so can't confirm one way or the other yet.

**Comment by f2prateek** [comment] 2015-08-11 23:44
@holmari I see, and you're not passing a custom executor either?

**Comment by holmari** [comment] 2015-08-12 06:55
@f2prateek we use the default executor. The stacktrace shows the executor too - we have exactly the same crash as @drspaceboo has, and based on the trace, I suppose they don't use a custom executor either.

**Comment by f2prateek** [comment] 2015-08-18 03:49
#331 and #332 address these issues, but I'm not entirely sure if it fixes since we don't have a reproducible case. They'll be released as snapshots, so if you can test those out, that would be immensely helpful.

**Comment by f2prateek** [comment] 2015-09-12 07:01
Closing this since I haven't heard back, but feel free to reopen with additional details if the issue persists  in the latest version.

**Closed by f2prateek** 2015-09-12 07:01 UTC
