### ISSUE TITLE
ConcurrentModificationException 

### ISSUE THREAD

**Issue by aminelaadhari** [segmentio/analytics-android#419] opened 2016-03-23 23:22 UTC
We have this error since the new version 4.0.8.

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:347)
       at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:376)
       at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:374)
       at java.util.AbstractMap.putAll(AbstractMap.java:380)
       at java.util.HashMap.putAll(HashMap.java:522)
       at com.segment.analytics.ValueMap.putAll(ValueMap.java:99)
       at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:203)
       at com.segment.analytics.Analytics.performRun(Analytics.java:1025)
       at com.segment.analytics.Analytics$4$1.run(Analytics.java:258)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5327)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by f2prateek** [comment] 2016-03-23 23:39
are you reusing the properties object?

**Comment by aminelaadhari** [comment] 2016-03-23 23:44
no

**Comment by nathanjones** [comment] 2016-03-26 14:11
I've been having the same crash occur. It seems to happen as soon as Segment initializes. My stack track looks the same as Amine's:

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
       at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:375)
       at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:373)
       at java.util.AbstractMap.putAll(AbstractMap.java:380)
       at java.util.HashMap.putAll(HashMap.java:504)
       at com.segment.analytics.ValueMap.putAll(ValueMap.java:99)
       at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:203)
       at com.segment.analytics.Analytics.performRun(Analytics.java:1025)
       at com.segment.analytics.Analytics$4$1.run(Analytics.java:258)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by f2prateek** [comment] 2016-03-26 19:23
Can either of you send a reproducible case?

**Comment by nathanjones** [comment] 2016-03-28 19:42
I haven't been able to find a consistent way to reproduce it, it's usually right as the app launches, but here's a more complete thread dump from Crashlytics:

http://crashes.to/s/2f3ce9c45be

**Comment by f2prateek** [comment] 2016-03-28 20:49
Are you using the options object in your code?

**Comment by f2prateek** [comment] 2016-03-28 20:52
W/o a reproducible hard to say - but the stack trace points to https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/IntegrationOperation.java#L203. So either `integrations` or `integrationOptions` is causing the error. It's unlikely `integrations` is causing the issue since it's allocated on the stack and not shared by threads.

`integrationOptions` is the likely culprit. This comes from when you either pass in options per call or `defaultOptions` in the builder. It looks like another thread from your app is accessing it while we're copying it.

**Comment by aminelaadhari** [comment] 2016-03-28 21:40
Is it safe to call track before all the integrations are ready ? (probably this is what happens here)

**Comment by f2prateek** [comment] 2016-03-28 21:59
Yes it is safe to call track before integrations are ready - can you clarify why you think that is causing an issue here? I don't think that is the issue.

**Comment by aminelaadhari** [comment] 2016-03-29 01:43
I thought that when an integration is ready it will modify existing TrackPayloads to add itself to them.

**Comment by f2prateek** [comment] 2016-03-29 05:38
@nathanjones @aminelaadhari are you using `Options` anywhere? If so, can you share the snippet?

**Comment by aminelaadhari** [comment] 2016-03-29 14:33
@f2prateek no I am not using it

**Comment by nathanjones** [comment] 2016-03-29 14:45
Here's all the code where I initialize all analytics platforms:

```
    private void initializeAnalytics() {

        String writeKey = getString(R.string.analytics_write_key);
        String optimizelyToken = getString(R.string.optimizely_token);

        Optimizely.setVerboseLogging(true);
        Optimizely.setVisualExperimentsEnabled(false);
        Optimizely.addOptimizelyEventListener(new DefaultOptimizelyEventListener(){

            @Override
            public void onOptimizelyExperimentVisited(OptimizelyExperimentData experimentState) {
                Analytics.with(getContext()).track("Experiment Viewed", new Properties()
                        .putValue("experimentId", experimentState.experimentId)
                        .putValue("experimentName", experimentState.experimentName)
                        .putValue("variationId", experimentState.variationId)
                        .putValue("variationName", experimentState.variationName));
            }
        });

        Analytics.Builder analyticsBuilder = new Analytics.Builder(getContext(), writeKey);

        if (BuildConfig.BUILD_TYPE.equals("debug")) {
            analyticsBuilder
                    .flushInterval(250, TimeUnit.MILLISECONDS)
                    .logLevel(Analytics.LogLevel.VERBOSE);
        }

        analyticsBuilder
                .use(AmplitudeIntegration.FACTORY)
                .use(MixpanelIntegration.FACTORY)
                .use(OptimizelyIntegration.createFactory(this, optimizelyToken));

        Analytics.setSingletonInstance(analyticsBuilder.build());

        String currentId = Analytics.with(getContext()).getAnalyticsContext().traits().currentId();

        MixpanelAPI
                .getInstance(getContext(), getContext().getString(R.string.mixpanel_token))
                .identify(currentId);
    }
```

Other than what you see here, the only interaction I have with Segment is calling `Analytics.track` & `Analytics.screen`

**Comment by aminelaadhari** [comment] 2016-03-29 15:10
We have too many crashes, I think I am downgrading to v4.0.4
http://crashes.to/s/f552c8d8387

**Comment by f2prateek** [comment] 2016-03-29 17:18
Nope this is from our library. I think I have a good idea but hard to verify if it works without a test case. I can submit a patch but I'll need help testing it out.

**Comment by aminelaadhari** [comment] 2016-03-29 17:35
Yes, sure when you have a snapshot version ready ping me, I will release a new version with it. Thanks!

**Comment by f2prateek** [comment] 2016-03-29 17:36
I've submitted a fix in #419 that will be merged and releases shortly. Please try it out let me know if it fixes the issue and we can cut 4.0.9 with it.

**Closed** 2016-03-29 17:58 UTC

**Comment by aminelaadhari** [comment] 2016-03-29 18:01
@f2prateek how can I get the snapshot ?

**Comment by f2prateek** [comment] 2016-03-29 18:05
These https://github.com/segmentio/analytics-java#snapshots instructions apply to our Android repo as well. once you've added that, just replace the version with 4.0.9-SNAPSHOT

**Comment by f2prateek** [comment] 2016-03-29 18:07
I'm also releasing 4.0.9 with this fix so if you can wait for an hour for that to be published, you don't need to try the snapshot.

**Comment by aminelaadhari** [comment] 2016-03-29 18:08
Ok thanks.

**Comment by nathanjones** [comment] 2016-03-30 00:40
I just pushed the 4.0.9 snapshot to the Play Store and this issue is still occurring.

**Comment by aminelaadhari** [comment] 2016-04-04 09:36
From our side it's fixed. Thanks @f2prateek!

**Comment by f2prateek** [comment] 2016-04-04 18:04
@nathanjones can you verify you were using the latest snapshot? Alternatively you can simply use 4.0.9

**Comment by f2prateek** [comment] 2016-04-04 18:05
@aminelaadhari Thanks for testing and confirming, I'm so sorry for introducing this bug!

**Comment by nathanjones** [comment] 2016-04-04 18:50
It may have been an issue with the version number on my reporting. I haven't seen that crash occur again so it looks like it's fixed. Thanks!
