### ISSUE TITLE
QueueFile crash

### ISSUE THREAD

**Issue by drspaceboo** [segmentio/analytics-android#172] opened 2015-02-10 04:47 UTC
We recently added the Segment IO SDK into our application. Since then we have seen an increasing number of crashes caused within the SDK due to Tape. It appears that an exception is being thrown but not handled.

This crash is now the 2nd most prevalent crash in our application.

Below is the stack trace we are getting via HockeyApp:
```
com.squareup.tape.FileException: Failed to remove.
	at com.squareup.tape.FileObjectQueue.remove(SourceFile:68)
	at com.segment.analytics.Segment.performFlush(SourceFile:123)
	at com.segment.analytics.Segment$SegmentHandler.handleMessage(SourceFile:181)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.os.HandlerThread.run(HandlerThread.java:60)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:419)
	at com.squareup.tape.QueueFile.ringRead(SourceFile:269)
	at com.squareup.tape.QueueFile.remove(SourceFile:506)
	at com.squareup.tape.FileObjectQueue.remove(SourceFile:65)
	... 5 more
```

While trying to debug it internally we also hit the following issue, however we're not sure if it is related:
```
 java.lang.ArrayIndexOutOfBoundsException: length=4096; regionStart=0; regionLength=-1629
            at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
            at libcore.io.IoBridge.write(IoBridge.java:491)
            at java.io.RandomAccessFile.write(RandomAccessFile.java:688)
            at com.segment.analytics.QueueFile.ringWrite(QueueFile.java:242)
            at com.segment.analytics.QueueFile.ringErase(QueueFile.java:251)
            at com.segment.analytics.QueueFile.remove(QueueFile.java:532)
            at com.segment.analytics.Segment.performFlush(Segment.java:151)
            at com.segment.analytics.Segment$SegmentHandler.handleMessage(Segment.java:301)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

We are using the Core library version 2.5.3.

**Comment by f2prateek** [comment] 2015-02-10 05:33
`FileObjectQueue` doesn't exist in the latest version, so I'm not sure how you're running into that issue. Can you make sure this is absolutely on the latest version?

**Comment by f2prateek** [comment] 2015-02-10 05:38
The second error is something we've had reported, I'm hoping to have it fixed for v3.

**Comment by drspaceboo** [comment] 2015-02-10 06:02
You're correct. I must have checked our latest development build and we have switched to a newer build and from All to Core.

Looks like our old version was using `2.4.6`. So when we release this new build that uses 2.5.3 Core we won't have the issue?

**Comment by aman400** [comment] 2015-02-26 03:36
Still have same issue with new newer build.. it crashes my application..

**Comment by f2prateek** [comment] 2015-02-26 04:50
Which build? Can you send the full stack trace?

**Comment by aman400** [comment] 2015-02-26 17:52
I'm using build v2.5.3.. here is the bug report..

java.lang.ArrayIndexOutOfBoundsException: length=4096; regionStart=0; regionLength=-1046
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
       at libcore.io.IoBridge.write(IoBridge.java:491)
       at java.io.RandomAccessFile.write(RandomAccessFile.java:688)
       at com.segment.analytics.QueueFile.ringWrite(QueueFile.java:242)
       at com.segment.analytics.QueueFile.ringErase(QueueFile.java:251)
       at com.segment.analytics.QueueFile.remove(QueueFile.java:532)
       at com.segment.analytics.Segment.performFlush(Segment.java:151)
       at com.segment.analytics.Segment$SegmentHandler.handleMessage(Segment.java:301)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
  Module "com.segment.analytics.Segment$SegmentHandler", line 301, in handleMessage
  Module "android.os.Handler", line 102, in dispatchMessage
  Module "android.os.Looper", line 135, in loop
  Module "android.os.HandlerThread", line 61, in run

**Comment by f2prateek** [comment] 2015-02-26 17:57
How are you initializing the Analytics client, and how are you sending events?

**Comment by aman400** [comment] 2015-02-27 03:52
I have a singleton class for using it..

public class SegmentAnalyticsSingleton
{
    private static Analytics analytics;
    public static Analytics getInstance(Context context)
    {
        if (analytics == null)
        {
            analytics = new Analytics.Builder(context, SegmentIO_key).build();
        }
        return analytics;
    }
}



In order to send event I use it like this:
SegmentAnalyticsSingleton.getInstance(context).track("button clicked");

**Comment by f2prateek** [comment] 2015-02-27 04:44
@aman400 , could you try the latest build (3.0.0) and enable logging and post the output here?

**Comment by aman400** [comment] 2015-02-27 05:18
okay, I'll give it a try. But the problem is that crash is random.

**Comment by adrien-aubel** [comment] 2015-03-13 23:49
With 3.0.1 I got this:
```
java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-1627682828
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
       at java.io.RandomAccessFile.readFully(RandomAccessFile.java:412)
       at com.segment.analytics.QueueFile.ringRead(QueueFile.java:276)
       at com.segment.analytics.QueueFile.remove(QueueFile.java:484)
       at com.segment.analytics.QueueFile.remove(QueueFile.java:456)
       at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Consistently prevents the app from starting. This is a major issue for us. Do you have any news about this issue?

**Comment by f2prateek** [comment] 2015-03-14 00:37
@adrien-aubel I think you're missing some logs there. `SegmentDispatcher.java:391` doesn't call the `remove` method.

**Comment by adrien-aubel** [comment] 2015-03-14 00:39
@f2prateek that's weird, this is what I got from Crashlytics. Release mode btw.

**Comment by f2prateek** [comment] 2015-03-14 00:41
@adrien-aubel weird, let me know if you see a more detailed log by any chance. We're updating the behaviour to handle this better in 3.0.2 (and we have been for a while), but it's hard to get a reproducible case to verify this behaviour.

**Comment by adrien-aubel** [comment] 2015-03-14 00:48
Could you maybe catch `ArrayIndexOutOfBoundsException` the same way you catch `IOException` every time you call `remove`?

**Comment by adrien-aubel** [comment] 2015-03-14 00:56
@f2prateek do you have any ETA for 3.0.2?

**Comment by adrien-aubel** [comment] 2015-03-14 01:29
Would you have by any chance steps that the user should follow if he wants to fix the problem without uninstalling the app and lose his data?

**Comment by appmagnetics** [comment] 2015-04-02 19:08
This issue is constantly on top of our Crashlytics statistics. Using 2.5.3.

java.lang.ArrayIndexOutOfBoundsException: length=4096; regionStart=0; regionLength=-1476
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
       at libcore.io.IoBridge.write(IoBridge.java:444)
       at java.io.RandomAccessFile.write(RandomAccessFile.java:689)
       at com.segment.analytics.QueueFile.ringWrite(QueueFile.java:242)
       at com.segment.analytics.QueueFile.ringErase(QueueFile.java:251)
       at com.segment.analytics.QueueFile.remove(QueueFile.java:532)
       at com.segment.analytics.Segment.performEnqueue(Segment.java:107)
       at com.segment.analytics.Segment$SegmentHandler.handleMessage(Segment.java:298)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by f2prateek** [comment] 2015-04-02 20:44
@appmagnetics try updating to 3.0.2

**Comment by appmagnetics** [comment] 2015-04-02 20:47
That's not so easy - I see in comments above someone trying 3.0.1 and saying it basically got worse - his app did not start. We cannot reproduce this issue by ourselves and we have 4000 customers for our app - we just cannot allow to release a new version and get the app crashed by them.

**Comment by adrien-aubel** [comment] 2015-04-02 22:27
@appmagnetics we didn't try 3.0.2 but since we were only using Mixpanel we unfortunately removed Segment.io to use directly Mixpanel SDK for the time being.
It was an easy switch for us since there was an abstraction on top of Segment.io, but depending on the time this would take you, you may consider a progressive rollout on the Google Play Store developer console instead.

**Comment by f2prateek** [comment] 2015-04-03 02:52
@appmagnetics @adrien-aubel How are you initializing the Analytics client - specifically the queueSize?

**Comment by appmagnetics** [comment] 2015-04-04 18:53
@f2prateek we do no special settings concerning queueSize or something else:

analytics = new Analytics.Builder(context, App.getString03()).build();

**Comment by f2prateek** [comment] 2015-04-04 21:08
How do you call use the analytics client? If it's through a helper class, can you share the implementation?

**Comment by appmagnetics** [comment] 2015-04-10 09:02
The issue can be actually fixed without further understanding, right? Either catch the exception of check boundaries before access. Will you be willing to fix 2.5.x version? If not, the discussion is worthless - if we want to avoid this crash we will have to try 3.x.x.

**Comment by f2prateek** [comment] 2015-04-10 14:23
We can't simply catch the exception - those items will be stuck in the disk queue forever and constantly be uploading. 

The issue is that queueFile is reporting it's size as 0 - a state that is explicitly disallowed. Either the bug is in our implementation, QueueFile or the data that's you're sending, and we don't know what the core issue is yet.

**Comment by f2prateek** [comment] 2015-04-14 16:32
@drspaceboo @appmagnetics @adrien-aubel @aman400 are you all using proguard?

**Comment by appmagnetics** [comment] 2015-04-14 20:15
Yes, we are using proguard

**Comment by drspaceboo** [comment] 2015-04-14 21:38
Yeah of course.

These are the rules we added for Segment IO:
```
#Segment IO
-dontwarn com.leanplum.**
-dontwarn com.bugsnag.**
-dontwarn com.segment.analytics.**
-dontwarn com.kahuna.sdk.**
```

These are the warnings we get if we don't have "dontwarn" turned on:
```
Warning: com.kahuna.sdk.location.KahunaGeofenceRemover: can't find superclass or interface com.google.android.gms.location.LocationClient$OnRemoveGeofencesResultListener
Warning: com.kahuna.sdk.location.KahunaGeofenceRequester: can't find superclass or interface com.google.android.gms.location.LocationClient$OnAddGeofencesResultListener
Warning: com.leanplum.activities.LeanplumSherlockActivity: can't find superclass or interface com.actionbarsherlock.app.SherlockActivity
Warning: com.leanplum.activities.LeanplumSherlockExpandableListActivity: can't find superclass or interface com.actionbarsherlock.app.SherlockExpandableListActivity
Warning: com.leanplum.activities.LeanplumSherlockFragmentActivity: can't find superclass or interface com.actionbarsherlock.app.SherlockFragmentActivity
Warning: com.leanplum.activities.LeanplumSherlockPreferenceActivity: can't find superclass or interface com.actionbarsherlock.app.SherlockPreferenceActivity
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find superclass or interface com.segment.analytics.internal.AbstractIntegration
Warning: com.kahuna.sdk.KahunaCoreReceiver: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.KahunaCoreReceiver: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.KahunaCoreReceiver: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.KahunaCoreReceiver: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.KahunaCoreReceiver: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRemover: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRemover: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRemover: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRemover: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRemover: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRemover: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRemover: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRequester: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRequester: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRequester: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRequester: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRequester: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRequester: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaActivityDetectionRequester: can't find referenced class com.google.android.gms.location.ActivityRecognitionClient
Warning: com.kahuna.sdk.location.KahunaGeofenceRemover: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.location.KahunaGeofenceRemover: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.location.KahunaGeofenceRemover: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.location.KahunaGeofenceRemover: can't find referenced class com.google.android.gms.location.LocationClient$OnRemoveGeofencesResultListener
Warning: com.kahuna.sdk.location.KahunaGeofenceRemover: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.location.KahunaGeofenceRequester: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.location.KahunaGeofenceRequester: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.location.KahunaGeofenceRequester: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.kahuna.sdk.location.KahunaGeofenceRequester: can't find referenced class com.google.android.gms.location.LocationClient$OnAddGeofencesResultListener
Warning: com.kahuna.sdk.location.KahunaGeofenceRequester: can't find referenced class com.google.android.gms.location.LocationClient
Warning: com.leanplum.activities.LeanplumSherlockActivity: can't find referenced class com.actionbarsherlock.app.SherlockActivity
Warning: com.leanplum.activities.LeanplumSherlockActivity: can't find referenced class com.actionbarsherlock.app.SherlockActivity
Warning: com.leanplum.activities.LeanplumSherlockActivity: can't find referenced class com.actionbarsherlock.app.SherlockActivity
Warning: com.leanplum.activities.LeanplumSherlockActivity: can't find referenced class com.actionbarsherlock.app.SherlockActivity
Warning: com.leanplum.activities.LeanplumSherlockActivity: can't find referenced class com.actionbarsherlock.app.SherlockActivity
Warning: com.leanplum.activities.LeanplumSherlockActivity: can't find referenced class com.actionbarsherlock.app.SherlockActivity
Warning: com.leanplum.activities.LeanplumSherlockActivity: can't find referenced class com.actionbarsherlock.app.SherlockActivity
Warning: com.leanplum.activities.LeanplumSherlockExpandableListActivity: can't find referenced class com.actionbarsherlock.app.SherlockExpandableListActivity
Warning: com.leanplum.activities.LeanplumSherlockExpandableListActivity: can't find referenced class com.actionbarsherlock.app.SherlockExpandableListActivity
Warning: com.leanplum.activities.LeanplumSherlockExpandableListActivity: can't find referenced class com.actionbarsherlock.app.SherlockExpandableListActivity
Warning: com.leanplum.activities.LeanplumSherlockExpandableListActivity: can't find referenced class com.actionbarsherlock.app.SherlockExpandableListActivity
Warning: com.leanplum.activities.LeanplumSherlockExpandableListActivity: can't find referenced class com.actionbarsherlock.app.SherlockExpandableListActivity
Warning: com.leanplum.activities.LeanplumSherlockExpandableListActivity: can't find referenced class com.actionbarsherlock.app.SherlockExpandableListActivity
Warning: com.leanplum.activities.LeanplumSherlockExpandableListActivity: can't find referenced class com.actionbarsherlock.app.SherlockExpandableListActivity
Warning: com.leanplum.activities.LeanplumSherlockFragmentActivity: can't find referenced class com.actionbarsherlock.app.SherlockFragmentActivity
Warning: com.leanplum.activities.LeanplumSherlockFragmentActivity: can't find referenced class com.actionbarsherlock.app.SherlockFragmentActivity
Warning: com.leanplum.activities.LeanplumSherlockFragmentActivity: can't find referenced class com.actionbarsherlock.app.SherlockFragmentActivity
Warning: com.leanplum.activities.LeanplumSherlockFragmentActivity: can't find referenced class com.actionbarsherlock.app.SherlockFragmentActivity
Warning: com.leanplum.activities.LeanplumSherlockFragmentActivity: can't find referenced class com.actionbarsherlock.app.SherlockFragmentActivity
Warning: com.leanplum.activities.LeanplumSherlockFragmentActivity: can't find referenced class com.actionbarsherlock.app.SherlockFragmentActivity
Warning: com.leanplum.activities.LeanplumSherlockFragmentActivity: can't find referenced class com.actionbarsherlock.app.SherlockFragmentActivity
Warning: com.leanplum.activities.LeanplumSherlockPreferenceActivity: can't find referenced class com.actionbarsherlock.app.SherlockPreferenceActivity
Warning: com.leanplum.activities.LeanplumSherlockPreferenceActivity: can't find referenced class com.actionbarsherlock.app.SherlockPreferenceActivity
Warning: com.leanplum.activities.LeanplumSherlockPreferenceActivity: can't find referenced class com.actionbarsherlock.app.SherlockPreferenceActivity
Warning: com.leanplum.activities.LeanplumSherlockPreferenceActivity: can't find referenced class com.actionbarsherlock.app.SherlockPreferenceActivity
Warning: com.leanplum.activities.LeanplumSherlockPreferenceActivity: can't find referenced class com.actionbarsherlock.app.SherlockPreferenceActivity
Warning: com.leanplum.activities.LeanplumSherlockPreferenceActivity: can't find referenced class com.actionbarsherlock.app.SherlockPreferenceActivity
Warning: com.leanplum.activities.LeanplumSherlockPreferenceActivity: can't find referenced class com.actionbarsherlock.app.SherlockPreferenceActivity
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Bugsnag
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Bugsnag
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Bugsnag
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Bugsnag
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Bugsnag
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Bugsnag
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Bugsnag
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Client
Warning: com.segment.analytics.BugsnagIntegration: can't find referenced class com.bugsnag.android.Client
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CountlyIntegration: can't find referenced class ly.count.android.api.Countly
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.CrittercismConfig
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.CrittercismConfig
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.CrittercismConfig
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.CrittercismConfig
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.Crittercism
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.Crittercism
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.Crittercism
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.Crittercism
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.Crittercism
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.Crittercism
Warning: com.segment.analytics.CrittercismIntegration: can't find referenced class com.crittercism.app.CrittercismConfig
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI$People
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI$People
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI$People
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI$People
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI$People
Warning: com.segment.analytics.MixpanelIntegration: can't find referenced class com.mixpanel.android.mpmetrics.MixpanelAPI
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced method 'boolean getBoolean(java.lang.String,boolean)' in program class com.segment.analytics.ValueMap
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced method 'java.lang.String getString(java.lang.String)' in program class com.segment.analytics.ValueMap
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.IdentifyPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.IdentifyPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced method 'org.json.JSONObject toJsonObject()' in program class com.segment.analytics.Traits
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.ScreenPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.ScreenPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.ScreenPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.Utils
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.ScreenPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.TrackPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.TrackPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced method 'org.json.JSONObject toJsonObject()' in program class com.segment.analytics.Properties
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced method 'double getDouble(java.lang.String,double)' in program class com.segment.analytics.Properties
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced method 'java.lang.String getString(java.lang.String)' in program class com.segment.analytics.Properties
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced method 'int getInt(java.lang.String,int)' in program class com.segment.analytics.Properties
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.Analytics$LogLevel
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.IdentifyPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.ScreenPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.Utils
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.TrackPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.Analytics$LogLevel
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.Analytics$LogLevel
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.IdentifyPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.IdentifyPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.ScreenPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.ScreenPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.TrackPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.model.payloads.TrackPayload
Warning: com.segment.analytics.internal.integrations.AmplitudeIntegration: can't find referenced class com.segment.analytics.internal.AbstractIntegration
```

**Comment by f2prateek** [comment] 2015-06-02 20:32
We've made some improvements in the latest versions that shouldn't cause this issue. Let me know if you still see any.

**Closed by f2prateek** 2015-06-02 20:32 UTC
Labels: bug
