### ISSUE TITLE
ArrayIndexOutOfBoundsException in QueueFile.remove()

### ISSUE THREAD

**Issue by kellyfj** [segmentio/analytics-android#263] opened 2015-04-23 12:28 UTC
Hi Prateek,

We discovered this during testing 

Version 3.0.3 - March 20th 2015

```
04-22 15:31:12.122    2050-2081/? E/AndroidRuntime﹕ FATAL EXCEPTION: SegmentAnalytics-SegmentDispatcher
    Process: com.here.hac.analytics.test, PID: 2050
    java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-1676930359
            at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:412)
            at com.segment.analytics.QueueFile.ringRead(QueueFile.java:261)
            at com.segment.analytics.QueueFile.remove(QueueFile.java:505)
            at com.segment.analytics.QueueFile.remove(QueueFile.java:477)
            at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:175)
            at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:404)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)​
```

**Comment by f2prateek** [comment] 2015-04-23 19:05
@kellyfj There is a potential fix for this in 3.1.0 - it doesn't catch this particular exception but should be able to recover on the next launch. Unless there is a reproducible case, we can't act on this alone.

For 3.1.1, I'm actually going to probably add some additional logging so it shows more context in the crash reports that will hopefully get us better insights into this.

**Comment by f2prateek** [comment] 2015-04-23 19:06
Related to #172

**Comment by kellyfj** [comment] 2015-04-27 22:38
I upgraded this morning to the latest 3.1.0 (technically it's labelled 3.1.1-SNAPSHOT) and still got the following during one test run

```
04-27 18:34:36.388    3838-4005/? W/dalvikvm﹕ threadid=99: thread exiting with uncaught exception (group=0xb0d59b20)
04-27 18:34:36.388    3838-4005/? E/AndroidRuntime﹕ FATAL EXCEPTION: SegmentAnalytics-SegmentDispatcher
    Process: com.here.hac.analytics.test, PID: 3838
    java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-2037311866
            at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:412)
            at com.segment.analytics.QueueFile.ringRead(QueueFile.java:261)
            at com.segment.analytics.QueueFile.remove(QueueFile.java:505)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:262)
            at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:201)
            at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
04-27 18:34:36.398    3838-4013/? E/Segment﹕ Payloads were rejected by server.
    com.segment.analytics.Client$UploadException: HTTP 400: Bad Request
            at com.segment.analytics.Client$1.close(Client.java:51)
            at com.segment.analytics.SegmentDispatcher.upload(SegmentDispatcher.java:232)
            at com.segment.analytics.SegmentDispatcher.access$000(SegmentDispatcher.java:42)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:257)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:255)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
04-27 18:34:36.398    1273-1391/system_process W/ActivityManager﹕ Error in app com.here.hac.analytics.test running instrumentation ComponentInfo{com.here.hac.analytics.test/android.test.InstrumentationTestRunner}:
04-27 18:34:36.398    1273-1391/system_process W/ActivityManager﹕ java.lang.ArrayIndexOutOfBoundsException
04-27 18:34:36.398    1273-1391/system_process W/ActivityManager﹕ java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-2037311866
04-27 18:34:36.588    3838-4012/? E/Segment﹕ Could not upload payloads.
    java.util.concurrent.ExecutionException: java.io.IOException: At least one payload must be provided.
            at java.util.concurrent.FutureTask.report(FutureTask.java:93)
            at java.util.concurrent.FutureTask.get(FutureTask.java:163)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:255)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:270)
            at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:201)
            at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.IOException: At least one payload must be provided.
            at com.segment.analytics.SegmentDispatcher$BatchPayloadWriter.endBatchArray(SegmentDispatcher.java:363)
            at com.segment.analytics.SegmentDispatcher.upload(SegmentDispatcher.java:226)
            at com.segment.analytics.SegmentDispatcher.access$000(SegmentDispatcher.java:42)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:257)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:255)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

```

**Comment by f2prateek** [comment] 2015-04-27 22:55
@kellyfj Is it a reproducible test run?

**Comment by kellyfj** [comment] 2015-04-27 23:03
Nope maybe 1 in 20 - although I will say the few times I've seen it I was generally getting a 400 bad request or 500 internal server error back from the server. Not sure if that helps to debug/diagnose?

**Comment by f2prateek** [comment] 2015-04-27 23:41
Yup it does, do you happen to have the exact responses returned by the server? I can try to simulate those conditions.

Additionally, our servers now return 200 regardless of whats sent to it, so you should make sure your proxy does the the same since we might not handle those responses correctly in our SDK.

**Comment by kellyfj** [comment] 2015-04-28 00:01
All I can see from the logs is a 400 and a 500. FYI our proxy is involved only on fetchSettings(). upload() calls communicate directly with Segment.

**Comment by f2prateek** [comment] 2015-04-28 04:34
Interesting, could you send us the son being uploaded next time you see a non-200 response on upload? Our SDK forms the JSON itself, so it should never be rejected by our servers.

**Comment by f2prateek** [comment] 2015-05-01 19:51
@kellyfj I've uploaded a new snapshot that adds more logging when this exception occurs. Should be available in a bit https://oss.sonatype.org/content/repositories/snapshots/com/segment/analytics/android/analytics-core/3.1.1-SNAPSHOT/

**Comment by kellyfj** [comment] 2015-05-01 20:20
Thanks - I'll take a stab at this on Monday. I think we've got a reproducible case when Queue gets up to 900+ elements. Hopefully can isolate it and create a test to send your way.

**Comment by f2prateek** [comment] 2015-05-01 20:37
Sweet, that would be perfect. Thanks!

**Closed** 2015-06-02 20:31 UTC

**Comment by benjamin-bader** [comment] 2015-07-01 17:02
Closed too soon, I think:

```
java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-2062708125
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
       at java.io.RandomAccessFile.readFully(RandomAccessFile.java:411)
       at com.segment.analytics.QueueFile.ringRead(QueueFile.java:261)
       at com.segment.analytics.QueueFile.remove(QueueFile.java:509)
       at com.segment.analytics.QueueFile.remove(QueueFile.java:477)
       at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:208)
       at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:445)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
