### ISSUE TITLE
Connection Resource Leak

### ISSUE THREAD

**Issue by Josh-Allen-ConnectedLab** [segmentio/analytics-android#588] opened 2018-08-01 13:20 UTC
We are seeing this in the logs with version 4.3.0:
W/OkHttpClient: A connection to https://api.segment.io/ was leaked. Did you forget to close a response body?

There's a resource leak somewhere in the Segment library.

There is also a community thread about this:
https://community.segment.com/t/y7lyfk/a-connection-to-httpsapi-segment-io-was-leaked

Thanks!

**Comment by f2prateek** [comment] 2018-08-01 18:39
Can you send a reproducible case for this?

**Comment by Josh-Allen-ConnectedLab** [comment] 2018-08-01 19:02
What would that look like? Do you have a sample app that stress tests your
library?

**Comment by f2prateek** [comment] 2018-08-01 19:52
We have one in this repo, see https://github.com/segmentio/analytics-android/tree/master/analytics-samples/analytics-sample.

**Comment by Josh-Allen-ConnectedLab** [comment] 2018-08-03 02:28
You need to go through your code and ensure you calling response.body().close in every case, 
https://github.com/square/okhttp/issues/2311

**Comment by f2prateek** [comment] 2018-08-03 07:12
The library does not use okhttp directly. It use the HTTPUrlConnection API, which internally uses OkHttp. We cannot call close on the internal response body as that's not exposed by the Android framework APIs.

The SDK does call disconnect on the connection
https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Client.java#L149.

If you see any concrete cases where we've missed this, let us know!

**Comment by twelve17** [comment] 2020-01-14 13:35
@f2prateek  Note that what needs to be closed is the *response body*, not just the connection, as stated in the error message:

> Did you forget to close a response body?

**Comment by twelve17** [comment] 2020-01-14 13:36
Whoops, my bad, I missed that last part of your comment. I got thrown off because I saw references to the response body in the linked Client.java class.

**Comment by twelve17** [comment] 2020-01-14 13:45
I noticed in a comment [in this answer|https://stackoverflow.com/q/50836831] that closing the input stream got rid of the error in their case.  

Is it possible this is not happening in some/all cases, here?

https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Client.java#L61

**Closed** 2020-03-02 21:36 UTC
Labels: needs info
