### ISSUE TITLE
UserID should be recorded at time of event.

### ISSUE THREAD

**Issue by wmontwe** [segmentio/analytics-android#522] opened 2017-04-06 10:41 UTC
While using Segment with Mixpanel integration for Android, I faced a racing condition when calling `alias` followed by `identify` like in the documentation described here: [Alias](https://segment.com/docs/sources/mobile/android/#alias)

Expected outcome: 
`anonymousId` is aliased to `userId` and then identified with `userId`

`analytics.alias("anonymousId", "userId");`
`analytics.identify("userId");`

But outcome is sometimes: 
`analytics.alias("userId", "userId");`
`analytics.identify("userId");`

So it seems like that even when `identify` is called after `alias`,  `alias` picks up the `userId` set by `identify` instead of `anonymousId`

**Comment by f2prateek** [comment] 2017-04-14 00:13
Yep, this is expected, though i agree it's surprising.
 The userId is set on the main thread (or whatever thread you call identify on), but read on a background thread. This means earlier events may pick the userId set by a new identify call.

An easy fix would be to read the userId on the main thread.

**Comment by f2prateek** [comment] 2017-04-24 23:34
I updated the title to better reflect the issue is. The source of the problem is that we don't record the userId when you call `track` or any of the methods, we do it a bit later.

**Comment by f2prateek** [comment] 2017-11-23 20:17
Tracking in https://segment.atlassian.net/browse/LIB-120

**Comment by cem2ran** [comment] 2018-01-29 11:51
@f2prateek has this issue been resolved?

**Comment by f2prateek** [comment] 2018-01-29 19:23
hey @cem2ran not yet. We'll close the issue and link to the code that improves this  when it's done.

**Closed** 2018-02-05 19:48 UTC
Labels: bug, jira
