### ISSUE TITLE
java.lang.NoSuchMethodError on application launch

### ISSUE THREAD

**Issue by SSead** [segmentio/analytics-android#745] opened 2021-02-10 10:48 UTC
I have updated my Gradle version in the project from 5.3.1 to 6.5.1 after which everything was working perfectly until my production builds started to fail with the following error:

```
 java.lang.NoSuchMethodError: 
  at com.segment.analytics.internal.Utils$NullableConcurrentHashMap.<init> (Utils.java:556)
  at com.segment.analytics.Traits$Cache.create (Traits.java:416)
  at com.segment.analytics.Traits$Cache.create (Traits.java:403)
  at com.segment.analytics.ValueMap$Cache.get (ValueMap.java:383)
  at com.segment.analytics.Analytics$Builder.build (Analytics.java:1332)
  at cc.mioo.data.analytics.AnalyticsImpl.<init> (AnalyticsImpl.kt:21)
  at cc.mioo.MainApp$analytics$2.invoke (MainApp.kt:52)
  at cc.mioo.MainApp$analytics$2.invoke (MainApp.kt:31)
  at kotlin.SynchronizedLazyImpl.getValue (LazyJVM.kt:74)
  at cc.mioo.MainApp.getAnalytics (Unknown Source:2)
  at cc.mioo.MainApp$applicationComponentBuilder$2.invoke (MainApp.kt:42)
  at cc.mioo.MainApp$applicationComponentBuilder$2.invoke (MainApp.kt:31)
  at kotlin.SynchronizedLazyImpl.getValue (LazyJVM.kt:74)
  at cc.mioo.MainApp.getApplicationComponentBuilder (Unknown Source:2)
  at cc.mioo.MainApp$applicationComponent$2.invoke (MainApp.kt:104)
  at cc.mioo.MainApp$applicationComponent$2.invoke (MainApp.kt:31)
  at kotlin.SynchronizedLazyImpl.getValue (LazyJVM.kt:74)
  at cc.mioo.MainApp.getApplicationComponent (Unknown Source:2)
  at cc.mioo.MainApp.onCreate (MainApp.kt:108)
  at cc.mioo.AndroidApp.onCreate (AndroidApp.kt:5)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1124)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5958)
  at android.app.ActivityThread.-wrap1 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1767)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:192)
  at android.app.ActivityThread.main (ActivityThread.java:6748)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:556)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:875)
```

I have managed to reproduce the bug and found that this happens when I call the `Analytics.build()` function with a key that was used on that device before. When I add a new key from the segment dashboard, the app launches successfully once, but every launch after that fails. This also happens when I use a completely random key.

My current version of segment analytics is 4.3.1. I tried upgrading to the newest release and this still keeps happening.

**Comment by prayansh** [comment] 2021-02-10 18:19
This seems to be a duplicate of #740. 
> Adding our [recommended proguard configuration](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#how-should-i-configure-proguard) should fix this issue

**Closed by prayansh** 2021-02-10 18:19 UTC

**Comment by emartynov** [comment] 2021-03-23 09:49
I just created #756
