### ISSUE TITLE
PlayStore rejecting app due to non-compliant with Google Play Policies 

### ISSUE THREAD

**Issue by omerhabib26** [segmentio/analytics-android#820] opened 2022-12-20 17:25 UTC
Playstore continuously rejects my app due to being non-compliant with Google Play Policies. After discussing with the support, they mentioned 
```
My App includes Segment SDK(4.10.4), which collects personal or sensitive data 
(Policy Declaration - Data Safety Section: Personal Info Data Type - Phone number).
You may consider upgrading to a policy-compliant version of this SDK that does not 
include the violating code if available from your SDK provider; moving to another SDK, 
or removing this SDK.
```
But on my side, we don't collect any kind of `Phone Number`.

**Comment by wenxi-zeng** [comment] 2023-01-03 16:59
hey @omerhabib26, sorry for the late response. can you confirm which version of the segment SDK are you using? if it's indeed 4.10.4, that's something new to us, since this version has gone through and passed google's privacy audit. something like this should not happen without a notice from google. we'll reach out to google to figure out the root cause, since the segment sdk does not collect phone number either.

**Comment by omerhabib26** [comment] 2023-01-03 17:02
Hey @wenxi-zeng thanks for replying. Yes we are using the 4.10.4  version.

**Comment by wenxi-zeng** [comment] 2023-01-03 19:29
@omerhabib26 thanks for the quick response! would you mind to forward that support email chain you had with google to wzeng@twilio.com? we can use that to jump start the communication with google. remember to remove any sensitive info before forwarding though. if you don't feel comfortable, that's totally fine :)

**Comment by tlalfano** [comment] 2023-01-03 21:34
Hi there @omerhabib26 ! Adding on to what Wenxi mentioned above, we have viewed the recent versions of the analytics-android sdk within the Google Play SDK Index Console and see no warnings or policy violations being raised by Google. Feel free to use this information when working with their support team!

**Comment by wenxi-zeng** [comment] 2023-01-17 16:45
hey @omerhabib26, haven't heard you back in 2 weeks. is the issue resolved? we also didn't get any policy violation reports from other customers. I'm assuming it's a false alarm from google's support team?

**Comment by omerhabib26** [comment] 2023-01-20 06:32
@wenxi-zeng sorry for the late respond can you please share ur email address?

**Comment by wenxi-zeng** [comment] 2023-01-20 16:21
@omerhabib26 no worries. my email is wzeng@twilio.com

**Comment by aminbahiraee** [comment] 2023-01-25 13:59
I use  version 4.11.0 and I found this issue  
`Your app includes SDK com.segment.analytics.android:analytics or an SDK that one of your libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers`

**Comment by omerhabib26** [comment] 2023-01-26 06:49
@wenxi-zeng sent ✅

**Comment by aminbahiraee** [comment] 2023-01-26 08:47
@wenxi-zeng  it is displayed in google play console when I submit the app, this is the full message: I already use `v4.11.0`

Your app My App version code 149 includes SDK com.segment.analytics.android:analytics or an SDK that one of your libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy.

Starting from October 1, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy may be blocked from release. You may consider upgrading to a policy-compliant version of this SDK that does not include the violating code if available from your SDK provider, or removing this SDK from your app.

According to your SDK provider, you may consider upgrading to 4.10.1, and/or contacting your SDK provider to see if a suitable later version might be available. Google is unable to endorse or recommend any third party software.

ACTION REQUIRED: Upload a new compliant version AND deactivate the noncompliant version.

Read through the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981#resubmit).

If you've reviewed the policy and feel our decision may have been in error, please reach out to our [policy support team](https://support.google.com/googleplay/android-developer/contact/appwarning?ts=sdk&src=com.segment.analytics.android:analytics).

[Learn More](https://support.google.com/googleplay/android-developer/answer/10358880)

**Comment by wenxi-zeng** [comment] 2023-01-26 16:06
thank you all for the quick responses. it's super helpful! just want you to know, this is our first priority now, will get back to you all as soon as we have a resolution.

**Comment by wenxi-zeng** [comment] 2023-01-30 20:48
hi @omerhabib26 and @aminbahiraee, we got a response from the google team. could you double check if your apps use the latest segment sdk in all active versions of the app in any track, production or non-production (Internal / Closed / Open testing)? please find below the instructions shared from google. also could both of you provide the full package name of your apps please? so the google team can have a look at the issues. thanks!

> It's also possible (likely) that the app developers are using old versions of your SDK in non-production tracks and that could be getting them caught up. Publishers who receive a notification should ensure all active versions of the app in any track, production or non-production (Internal / Closed / Open testing), have migrated off the non-aligned SDK version or removed the SDK. The developer can also resolve the issue by deactivating any tracks that contain an active version of the app that has not addressed the issue during new submission. Here are our standard step-by-step instructions that you can share with these publishers on how to update a non-compliant version of an APK (we’ll encourage the same from our side, and detailed guidance on how to prepare and roll out a release is [here](https://urldefense.com/v3/__https://support.google.com/googleplay/android-developer/answer/9859348?hl=en&ref_topic=7072031__;!!NCc8flgU!dx3uaqrieogZaK3SWTs79hoPYQFDr5iFpT-f-LMafGCbQQJJi0kGq-A0JTwx4GJUdKqnJ7WJ5pCjz4OC$).):
> 1. Go to your [Play Console](https://play.google.com/console/)
> 2. Select the app
> 3. Go to App bundle explorer
> 4. Select the violating APK/app bundle's App version at the top right dropdown menu, and make a note of which releases they are under
> 5. Go to the track with the violation. It will be one of these 4 pages: Internal / Closed / Open testing or Production
> 6. Near the top right of the page, click Create new release. (You may need to click Manage track first); If the release with the violating APK is in a draft state, discard the release
> 7. Add the new version of app bundles or APKs; Make sure the non-compliant version of app bundles or APKs is under the Not included section of this release
> 8. To save any changes you make to your release, select Save
> 9. When you've finished preparing your release, select Review release, and then proceed to roll out the release to 100%.
> 10. If the violating APK is released to multiple tracks, repeat steps 5-9 in each track

**Comment by aminbahiraee** [comment] 2023-02-08 12:36
@wenxi-zeng  it is fixed, thank you. we had some testing tracks that used older versions, I updated them and the issue is fixed now.

**Comment by wenxi-zeng** [comment] 2023-02-13 17:58
@omerhabib26 haven't heard back from you for a while. I'm assuming google's instructions have addressed your issue as well. closing this ticket now. if you still experience issues, feel free to reopen this issue. thanks!

**Closed by wenxi-zeng** 2023-02-13 17:58 UTC

**Comment by omerhabib26** [comment] 2023-02-13 18:02
@wenxi-zeng sorry for the late response I was busy with other things. Google hasn’t addressed the issue as their support team isn't responding we are still waiting from their side.

**Comment by wenxi-zeng** [comment] 2023-02-13 22:36
@omerhabib26 oh. sorry, I meant if [these instructions](https://github.com/segmentio/analytics-android/issues/820#issuecomment-1409311562) have addressed your issue?

**Comment by omerhabib26** [comment] 2023-02-15 08:49
@wenxi-zeng ye tried these steps multiple times but in the end, we have to update the SafetyForm and checked the `Data Safety Section: Personal Info Data Type - Phone number` so we can rollout the release.
