### ISSUE TITLE
Queue not flushed or counter not reset?

### ISSUE THREAD

**Issue by wjwarren** [segmentio/analytics-android#167] opened 2015-02-05 16:23 UTC
When looking at the Segment Debugger website and comparing it to the LogCat output, there seems to be a discrepancy. I can see the events showing up on the Debugger website (https://segment.com/[user]/[project]/debugger), but the LogCat output shows no indication that the queue has actually been flushed.

I use the default 20 events limit, have a working internet connection, but end up with a much higher number of items in the queue.

```bash
D/Segment﹕ Segment    enqueue    a212bfc5-7f12-4bdc-b7df-744b04592fbf {queueSize: 58}
```

Is the Debugger website showing something incorrect or is there an error in your log(cat) messages?

**Comment by f2prateek** [comment] 2015-02-05 19:58
We removed logging messages when they get flushed since we don't actually deserialize them. This is fixed in v3, where we'll just display the number of events flushed (and no other data).

You can use `Analytics#getStats` to see the number of events that have been flushed in a session.

The queueSize can grow in size beyond the flushSize - if say our servers are down. Occasionally an upload also might be completed, but we might not have received a 200 response from the server - so we don't remove it from the disk queue. We'll just try uploading it again, and since payloads are idempotent, our server will simply discard the repeated request.

**Comment by wjwarren** [comment] 2015-02-05 20:22
Thanks again for the quick reply and the explanation! :)

**Comment by lukeweber** [comment] 2015-02-06 06:39
Interesting thing happened, and we have a support case open, but wanted to ping this thread. Yesterday, we were testing our app, opened a few pages, registered, created some content. In all maybe it's 150 events through our testing. If we killed the app and reopened it would resend those 150 events each time the app was opened, maybe it was even doubling them each time which would make more sense with the numbers that I'm getting, but it's hard to be sure because I don't have a very good view of the raw data. I had to delete this project in segment to stop the pain as it had amassed 500k "requests" from just three phones in basically three days and my segment was complaining that I had far surpassed my quota when we usually would only use 500 requests or so in this same time period.

Curious if you could think of a case that would trigger this kind of doubling of data sent to the point that 1 phone could generate in the hundreds of thousands of events, which is what we've seen. We've since tried to reproduce this on a new segment project and I haven't yet, but since it was doing this yesterday and now isn't I'm a little curious if the sdk doesn't have a race case problem that could cause this behavior.

Also I was using charles a bit for my own app, which might have temporarily blocked ssl connections to segment.io. I'll toy around with doing this as well to see if it has an impact.

**Comment by f2prateek** [comment] 2015-02-06 17:10
@lukeweber interesting, I doubt think it's a race problem - the queue is only ever accessed from one thread. It could certainly be from a different issue.

If anything - you would be seeing events being dropped. If we're flushing events and you've submitted more events, the queue won't be able to accept them until the flush finishes (since the enqueue/dequeue and flush are run on a single thread).

Is this on the latest version of the library?

**Comment by lukeweber** [comment] 2015-02-06 18:11
Yes it's on 2.5.3.

I had to delete the project that it was related to in segment ledge/dev
because I noticed late at night and thought it might have been our issue
and there's no way to revoke a key. Two days later, we haven't reproduced
this again yet, but I'm focusing on that today as it was happening on three
different phones on that project.

On Fri, Feb 6, 2015 at 9:10 AM, Prateek Srivastava <notifications@github.com

**Comment by f2prateek** [comment] 2015-02-06 18:21
@lukeweber Ah I think your issue was a server side issue - we couldn't debug it since you deleted the project. Let us know if it happens again and we'll look up the logs for our project to narrow down the problem.

**Comment by lukeweber** [comment] 2015-02-06 18:35
It's just started happening right now on wijnand/test. It only happens when
we're hooked up to mixpanel, which we've now temporarily disabled just so
we don't hammer your servers servers or mixpanel's.

If you want to ping me directly or hangout, I've sent you an email with the
details.

**Comment by f2prateek** [comment] 2015-02-06 18:42
@lukeweber thanks, looking into it now. To confirm, the debugger shows you messages correctly (i.e. without duplicates) - but Mixpanel is showing it duplicate events?

**Comment by lukeweber** [comment] 2015-02-06 18:44
Another interesting point about this. Once this starts happening, if you kill the app and reopen it sends a lot of events to segment. Then do nothing in the app and about 10 seconds later it send the same chunk of data again and again.

**Comment by lukeweber** [comment] 2015-02-06 18:45
On the debugger we're seeing way too many events coming past.

**Comment by f2prateek** [comment] 2015-02-12 04:38
(Already done in v3, closing for now)

**Closed by f2prateek** 2015-02-12 04:38 UTC
Labels: bug
