### ISSUE TITLE
StrictMode: A resource was acquired at attached stack trace but never released

### ISSUE THREAD

**Issue by kierse** [segmentio/analytics-android#462] opened 2016-07-22 16:07 UTC
We use StrictMode in development and started seeing the following error after upgrading to 4.1.4. We've since stopped using Segment while in development so I can't comment as to whether or not 4.1.5 fixes the problem.

This error comes from Android 6.0 running in Genymotion, but we've encountered it across various versions of Android (in VM and on physical devices) starting from 4.4 and newer 

``` java
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
              java.lang.Throwable: Explicit termination method 'end' not called
                  at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                  at java.util.zip.Deflater.<init>(Deflater.java:192)
                  at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:81)
                  at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:54)
                  at com.segment.analytics.Client.createPostConnection(Client.java:51)
                  at com.segment.analytics.Client.upload(Client.java:92)
                  at com.segment.analytics.SegmentIntegration.performFlush(SegmentIntegration.java:289)
                  at com.segment.analytics.SegmentIntegration.access$100(SegmentIntegration.java:45)
                  at com.segment.analytics.SegmentIntegration$3.run(SegmentIntegration.java:266)
                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                  at java.lang.Thread.run(Thread.java:818)
                  at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:408)
```

**Comment by f2prateek** [comment] 2016-07-27 18:20
AFAICT we're definitely calling close, but I'll take a look.

**Comment by peterkallstrom** [comment] 2016-11-16 10:24
I'm seeing a similar issue using v4.2.4. Below is a log running on Android 5.1.1.

```
11-16 11:07:54.847 16204-16270/com.example.launcher V/Analytics: Created payload ScreenPayload{name="Launcher,category="null"}.
11-16 11:07:54.849 16204-16270/com.example.launcher V/Analytics: Created payload TrackPayload{event="Button pressed"}.
11-16 11:07:54.946 16204-16214/com.example.launcher E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                 java.lang.Throwable: Explicit termination method 'end' not called
                                                                     at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                     at java.util.zip.Inflater.<init>(Inflater.java:82)
                                                                     at com.android.okio.GzipSource.<init>(GzipSource.java:57)
                                                                     at com.android.okhttp.internal.http.HttpEngine.initContentStream(HttpEngine.java:490)
                                                                     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:680)
                                                                     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
                                                                     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
                                                                     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
                                                                     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                                                                     at com.segment.analytics.Analytics.trackAttributionInformation(Analytics.java:316)
                                                                     at com.segment.analytics.Analytics$3$1.run(Analytics.java:259)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
11-16 11:07:55.547 16204-16312/com.example.launcher V/Analytics: Enqueued {messageId=1aef73f0-a5e2-49ac-b1f9-d88ac0c307d2, type=screen, channel=mobile, context={app={build=10, name=Launcher, namespace=com.example.launcher, version=1.0}, traits={anonymousId=d71db1f0-e608-432d-ac2c-77f7a3b90deb}, library={name=analytics-android, version=4.2.4}, os={name=Android, version=5.1.1}, timezone=Europe/Amsterdam, screen={density=1.0, width=320, height=480}, userAgent=Dalvik/2.1.0 (Linux; U; Android 5.1.1; SH1 Build/seprjpka.20161102.090845), locale=en-US, device={id=41bd5ab4dd3b1397, manufacturer=Ascom, model=SH1, name=AABA}, network={carrier=}}, anonymousId=d71db1f0-e608-432d-ac2c-77f7a3b90deb, timestamp=2016-11-16T11:07:54+0100, integrations={}, category=null, name=Launcher, properties={}} payload. 1 elements in the queue.
11-16 11:07:55.721 16204-16312/com.example.launcher V/Analytics: Enqueued {messageId=a5986096-ec16-4383-9153-22e65167cacc, type=track, channel=mobile, context={app={build=10, name=Launcher, namespace=com.example.launcher, version=1.0}, traits={anonymousId=d71db1f0-e608-432d-ac2c-77f7a3b90deb}, library={name=analytics-android, version=4.2.4}, os={name=Android, version=5.1.1}, timezone=Europe/Amsterdam, screen={density=1.0, width=320, height=480}, userAgent=Dalvik/2.1.0 (Linux; U; Android 5.1.1; SH1 Build/seprjpka.20161102.090845), locale=en-US, device={id=41bd5ab4dd3b1397, manufacturer=Ascom, model=SH1, name=AABA}, network={carrier=}}, anonymousId=d71db1f0-e608-432d-ac2c-77f7a3b90deb, timestamp=2016-11-16T11:07:54+0100, integrations={}, event=Button pressed, properties={name=Home}} payload. 2 elements in the queue.
```

**Comment by tadfisher** [comment] 2017-03-28 21:13
Seeing this in v4.2.6, Android 7.1.2:

```
03-28 14:11:32.113 1571-1580/com.banksimple E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                          java.lang.Throwable: Explicit termination method 'end' not called
                                                              at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                              at java.util.zip.Inflater.<init>(Inflater.java:104)
                                                              at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
                                                              at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                                                              at com.segment.analytics.Analytics.trackAttributionInformation(Analytics.java:316)
                                                              at com.segment.analytics.Analytics$3$1.run(Analytics.java:259)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                              at java.lang.Thread.run(Thread.java:761)
```

**Comment by carlbenson** [comment] 2017-08-08 14:03
I get 
```
W/OkHttpClient: A connection to https://api.segment.io/ was leaked. Did you forget to close a response body?
```
Also on 4.2.6. Is this fixed in 4.3.0?

**Comment by f2prateek** [comment] 2017-11-06 22:07
@carlbenson sorry for the delay here. another user reported this as well. https://twitter.com/BenoitLetondor/status/927544518827757568

Could you send some details on reproducing? I don't see any warnings when I run our sample app.

**Comment by f2prateek** [comment] 2017-11-23 21:42
Tracking internally in JIRA https://segment.atlassian.net/browse/LIB-122

We still haven't been able to reproduce this - if anyone can share the steps for reproducing it, that'd be great!

**Comment by eygraber** [comment] 2018-02-23 00:37
https://github.com/segmentio/analytics-android/issues/554#issuecomment-367870719

**Comment by kushalkadaba** [comment] 2018-03-08 20:10
This seems to be a bigger problem than just segment. Getting these warnings even from Newstand app. Looks like it's related to https://github.com/square/okhttp/issues/2311. 

Could be solved by wrapping the HttpUrlConnection object so that it closes the input stream. 
`class CustomConnectionFactory extends ConnectionFactory {

    @Override
    public HttpURLConnection upload(String writeKey) throws IOException {
        HttpURLConnection httpURLConnection = super.upload(writeKey);
        return createClosingConnectionWrapper(httpURLConnection);
    }

    private HttpURLConnection createClosingConnectionWrapper(HttpURLConnection connection) {
        return new HttpURLConnection(connection.getURL()) {
            @Override
            public void disconnect() {
                InputStream inputStream = null;
                try {
                    inputStream = connection.getInputStream();
                } catch (IOException e) {
                    e.printStackTrace();
                } finally {
                    if (inputStream != null) {
                        try {
                            inputStream.close();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }
                }
                connection.disconnect();
            }

            @Override
            public boolean usingProxy() {
                return connection.usingProxy();
            }

            @Override
            public void connect() throws IOException {
                connection.connect();
            }

            @Override
            public String getHeaderFieldKey(int n) {
                return connection.getHeaderFieldKey(n);
            }

            @Override
            public void setFixedLengthStreamingMode(int contentLength) {
                connection.setFixedLengthStreamingMode(contentLength);
            }

            @Override
            public void setFixedLengthStreamingMode(long contentLength) {
                connection.setFixedLengthStreamingMode(contentLength);
            }

            @Override
            public void setChunkedStreamingMode(int chunklen) {
                connection.setChunkedStreamingMode(chunklen);
            }

            @Override
            public String getHeaderField(int n) {
                return connection.getHeaderField(n);
            }

            @Override
            public void setInstanceFollowRedirects(boolean followRedirects) {
                connection.setInstanceFollowRedirects(followRedirects);
            }

            @Override
            public boolean getInstanceFollowRedirects() {
                return connection.getInstanceFollowRedirects();
            }

            @Override
            public void setRequestMethod(String method) throws ProtocolException {
                connection.setRequestMethod(method);
            }

            @Override
            public String getRequestMethod() {
                return connection.getRequestMethod();
            }

            @Override
            public int getResponseCode() throws IOException {
                return connection.getResponseCode();
            }

            @Override
            public String getResponseMessage() throws IOException {
                return connection.getResponseMessage();
            }

            @Override
            public long getHeaderFieldDate(String name, long Default) {
                return connection.getHeaderFieldDate(name, Default);
            }

            @Override
            public Permission getPermission() throws IOException {
                return connection.getPermission();
            }

            @Override
            public InputStream getErrorStream() {
                return connection.getErrorStream();
            }

            @Override
            public OutputStream getOutputStream() throws IOException {
                return connection.getOutputStream();
            }

            @Override
            public void setConnectTimeout(int timeout) {
                connection.setConnectTimeout(timeout);
            }

            @Override
            public int getConnectTimeout() {
                return connection.getConnectTimeout();
            }

            @Override
            public void setReadTimeout(int timeout) {
                connection.setReadTimeout(timeout);
            }

            @Override
            public int getReadTimeout() {
                return connection.getReadTimeout();
            }

            @Override
            public URL getURL() {
                return connection.getURL();
            }

            @Override
            public int getContentLength() {
                return connection.getContentLength();
            }

            @Override
            public long getContentLengthLong() {
                return connection.getContentLengthLong();
            }

            @Override
            public String getContentType() {
                return connection.getContentType();
            }

            @Override
            public String getContentEncoding() {
                return connection.getContentEncoding();
            }

            @Override
            public long getExpiration() {
                return connection.getExpiration();
            }

            @Override
            public long getDate() {
                return connection.getDate();
            }

            @Override
            public long getLastModified() {
                return connection.getLastModified();
            }

            @Override
            public String getHeaderField(String name) {
                return connection.getHeaderField(name);
            }

            @Override
            public Map<String, List<String>> getHeaderFields() {
                return connection.getHeaderFields();
            }

            @Override
            public int getHeaderFieldInt(String name, int Default) {
                return connection.getHeaderFieldInt(name, Default);
            }

            @Override
            public long getHeaderFieldLong(String name, long Default) {
                return connection.getHeaderFieldLong(name, Default);
            }

            @Override
            public Object getContent() throws IOException {
                return connection.getContent();
            }

            @Override
            public Object getContent(Class[] classes) throws IOException {
                return connection.getContent(classes);
            }

            @Override
            public InputStream getInputStream() throws IOException {
                return connection.getInputStream();
            }

            @Override
            public String toString() {
                return connection.toString();
            }

            @Override
            public void setDoInput(boolean doinput) {
                connection.setDoInput(doinput);
            }

            @Override
            public boolean getDoInput() {
                return connection.getDoInput();
            }

            @Override
            public void setDoOutput(boolean dooutput) {
                connection.setDoOutput(dooutput);
            }

            @Override
            public boolean getDoOutput() {
                return connection.getDoOutput();
            }

            @Override
            public void setAllowUserInteraction(boolean allowuserinteraction) {
                connection.setAllowUserInteraction(allowuserinteraction);
            }

            @Override
            public boolean getAllowUserInteraction() {
                return connection.getAllowUserInteraction();
            }

            @Override
            public void setUseCaches(boolean usecaches) {
                connection.setUseCaches(usecaches);
            }

            @Override
            public boolean getUseCaches() {
                return connection.getUseCaches();
            }

            @Override
            public void setIfModifiedSince(long ifmodifiedsince) {
                connection.setIfModifiedSince(ifmodifiedsince);
            }

            @Override
            public long getIfModifiedSince() {
                return connection.getIfModifiedSince();
            }

            @Override
            public boolean getDefaultUseCaches() {
                return connection.getDefaultUseCaches();
            }

            @Override
            public void setDefaultUseCaches(boolean defaultusecaches) {
                connection.setDefaultUseCaches(defaultusecaches);
            }

            @Override
            public void setRequestProperty(String key, String value) {
                connection.setRequestProperty(key, value);
            }

            @Override
            public void addRequestProperty(String key, String value) {
                connection.addRequestProperty(key, value);
            }

            @Override
            public String getRequestProperty(String key) {
                return connection.getRequestProperty(key);
            }

            @Override
            public Map<String, List<String>> getRequestProperties() {
                return connection.getRequestProperties();
            }
        };
    }
}
`

**Comment by prayansh** [comment] 2020-11-10 01:06
We no longer use OkHttp in our library and i believe this PR should have covered this Strict warning https://github.com/segmentio/analytics-android/pull/642/files :). Please reopen if that is not the caase

**Closed by prayansh** 2020-11-10 01:06 UTC
Labels: bug, jira
