### ISSUE TITLE
NPE when sdk is initialized(Empty ProjectSettings Object)

### ISSUE THREAD

**Issue by Arthien** [segmentio/analytics-android#525] opened 2017-04-19 19:30 UTC
We are having an issue that appears randomly when running this SDK. We have tried both our production app and the sample app provided by segment docs, but we have the issue no matter the implementation. 

```
[ERROR] AndroidRuntime: FATAL EXCEPTION: main
[ERROR] AndroidRuntime: Process: com.fanhero.staging, PID: 23438
[ERROR] AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'com.segment.analytics.ValueMap com.segment.analytics.ValueMap.getValueMap(java.lang.Object)' on a null object reference
[ERROR] AndroidRuntime: 	at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1290)
[ERROR] AndroidRuntime: 	at com.segment.analytics.Analytics$2$1.run(Analytics.java:240)
[ERROR] AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
[ERROR] AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7237)
[ERROR] AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
I noticed that creating a new segment source and providing a different segment key occasionally fixed this issue.

Using the latest segment SDK.
Reproduced with and without any integrations.

**Comment by f2prateek** [comment] 2017-04-23 05:32
Hey @Arthien, could you write in to friends@segment.Com and cc prateek@segment.com with more details such as your writeKey?

**Comment by f2prateek** [comment] 2017-04-24 23:58
We tested our sample apps using a a few different writeKeys (including the one you sent in your ticket) on both 4.2.6 branch and master, but couldn't reproduce the behaviour you are seeing. Teresa from our team will follow up with more questions and help debug this further.

The case your stack trace is describing shouldn't be possible (empty project settings). We could have a guard against it, but I'd like to understand why this would be happening before doing so. This is so that do don't inadvertently hide a genuine bug.

Since there isn't any immediate action here, I'm closing this issue for now. Once we can understand the root cause  better and verify this is indeed an error in the SDK, we'll reopen and discuss possible solutions.

**Closed by f2prateek** 2017-04-24 23:58 UTC

**Comment by Arthien** [comment] 2017-04-25 16:58
Thanks for the information @f2prateek. When can I expect this follow up?

**Comment by f2prateek** [comment] 2017-04-25 17:27
@Arthien definitely should be hearing from us today!
