### ISSUE TITLE
IntegrationOperation is leaking activity

### ISSUE THREAD

**Issue by aminelaadhari** [segmentio/analytics-android#334] opened 2015-08-21 10:39 UTC
Hey, we detected a memory leak with version 3.1.6, here a screenshot of the stack using leak canary:
![screenshot_2012-01-02-19-18-15](https://cloud.githubusercontent.com/assets/1357594/9406472/04837a50-4801-11e5-8d78-9b8a0f465718.png)

To reproduce, the scenario is quite simple  :
Start an activity and immediately call finish and start another.

With a device like Samsung Galaxy note 2 (GT-N7100) it is systematic.

Let me know if you need more info

**Comment by f2prateek** [comment] 2015-10-24 20:38
I think I finally figured out a fix for this, I should have it ready end of the week!

**Comment by aminelaadhari** [comment] 2015-10-25 04:37
great thanks !

**Comment by nizamcs** [comment] 2015-12-02 11:55
@f2prateek Is this one fixed now?

**Comment by f2prateek** [comment] 2015-12-03 02:28
Not yet.

**Comment by nizamcs** [comment] 2015-12-15 05:18
Hi Prateek,

In that case, is there a stable previous version that we can use for the
time being? I need only analytics-core. It's been a bit long time since we
parked the segment integration because of this issue. Please do the needful.

Regards,



*Nizam CS*

*Senior Software Engineer*

Email: nizam.ls@accedo.tv

www.accedo.tv

**Comment by f2prateek** [comment] 2015-12-15 15:41
What do you mean previous version?

**Comment by f2prateek** [comment] 2015-12-15 15:48
I'm adding a label of wontfix to this bug.

The issue is here is that Segment holds on activities when we register for the lifecycle callbacks. We need to hold on to these so we can send those events to integrations.

Because of this, if you close an activity faster than we can forward the event to an integration, you'll see LeakCanary complain.

In most cases, we can send the event faster than you can close the app. But we can't when we're launching for the very first time (not on every launch, but just right after the app is installed) we don't have any settings and we need to ask the server to figure out which integrations to initialize.

This is used a be a real issue in older versions, because if we couldn't connect to the internet, we'd end up holding the activity references forever.

In the new version however, we fallback gracefully and initialize only the Segment integration, so we don't hold those references indefinitely.

**Closed by f2prateek** 2015-12-15 15:48 UTC
Labels: bug, wontfix

**Comment by aminelaadhari** [comment] 2015-12-15 16:00
Thanks Prateek for making things clear.

> In the new version however, we fallback gracefully and initialize only the Segment integration, so we don't hold those references indefinitely.

Starting form which version ?

**Comment by f2prateek** [comment] 2015-12-15 16:04
@aminelaadhari This is from 4.x onwards.
