### ISSUE TITLE
java.io.FileNotFoundException: https://api.segment.io/v1/import

### ISSUE THREAD

**Issue by pandey-adarsh147** [segmentio/analytics-android#430] opened 2016-05-18 11:50 UTC
Payloads were rejected by server. Marked for removal.
                                                                com.segment.analytics.Client$UploadException: HTTP 400: Bad Request. Response: Could not read response body for rejected message: java.io.FileNotFoundException: https://api.segment.io/v1/import

I am keep getting this.

**Comment by f2prateek** [comment] 2016-05-18 14:23
Do you have a reproducible case?

**Comment by f2prateek** [comment] 2016-05-24 00:33
Closing since the SDK handles this gracefully, please re-open if you have a reproducible case and we can investigate the cause.

**Closed by f2prateek** 2016-05-24 00:33 UTC
