### ISSUE TITLE
Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by snadjafi** [segmentio/analytics-android#490] opened 2017-01-05 00:11 UTC
I am using `v4.2.1` and I am getting this error. I thought I should report this.

```
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:730)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1348)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:89)
       at com.segment.analytics.SegmentIntegration.submitFlush(SegmentIntegration.java:270)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:450)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by f2prateek** [comment] 2017-01-05 00:50
Can you share a reproducible case?

**Comment by f2prateek** [comment] 2017-01-05 20:43
@nayrban @snadjafi to be clear, this is from your logs and not actually crashing your app?

**Comment by snadjafi** [comment] 2017-01-05 21:03
@f2prateek This is from my logs and it is crashing my app but I am trying to reproduce it but I am not able to reproduce it. The past week I had 20 crashes and daily daily active users are around 6000 people. 
Take a look at this: http://crashes.to/s/d80c97fab71

**Comment by f2prateek** [comment] 2017-01-05 21:12
@snadjafi are you calling analytics.shutdown anywhere?

**Comment by snadjafi** [comment] 2017-01-05 21:22
@f2prateek no. I only call `flush()` and `rest()` if the user log out which is not the case base on the log details.

**Comment by f2prateek** [comment] 2017-01-05 21:25
@snadjafi i see, are you maybe setting a custom network executor?

**Comment by snadjafi** [comment] 2017-01-05 21:53
@f2prateek I don't create any but other libs in my project probably they probably do. For example Fabric, Optimizely or Retrofit probably they do.

**Comment by f2prateek** [comment] 2017-01-05 21:58
@snadjafi sorry what I meant was do you create and set a custom network executor on the Analytics class https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L1096-L1109.

**Comment by snadjafi** [comment] 2017-01-05 22:04
@f2prateek ooh nope.

**Comment by f2prateek** [comment] 2017-01-05 22:22
From what I can tell, this exception should only be thrown occur if the application process is being shut down in the case of a fatal error (see https://github.com/ACRA/acra/issues/332 and https://twittercommunity.com/t/thread-native-create-errors/70458). Based on these issues, it could be because this manifests only when specific UncaughtExceptionHandlers implemented a certain way are installed.

In either case, if there are events in flight to segment, there's a chance that during this runtime shutdown phase Segment will try to upload an event.

I tried by crashing the app with in flight events to Segment, and didn't see this error be thrown, so I'm hesitant to just catch internal errors thrown by the executor, because that could hide other problems and this is not a reproducible case. 

If you can play around with this scenario in your apps to verify the cause, that'd get us much closer to a solution!

**Comment by snadjafi** [comment] 2017-01-05 23:03
@f2prateek that makes sense since this is only happening in 1 screen which tells me that the application is crashing for another reason and it's effecting this too. I really appreciate your help. I will do more investigation and get back to you if I find anything else.

**Comment by f2prateek** [comment] 2017-03-09 00:12
Closing this issue as there doesn't seem to be any action for us to take, but let us know if there are any updates!

**Closed by f2prateek** 2017-03-09 00:12 UTC
