### ISSUE TITLE
Application Installed is fired multiple times for app install

### ISSUE THREAD

**Issue by littlehome-eugene** [segmentio/analytics-android#638] opened 2020-01-08 19:36 UTC
We are seeing 3x more app installed compared to playstore app install stats..

What could be the reason?

**Comment by aultimus** [comment] 2020-03-20 17:57
Hi @littlehome-eugene , I implemented a fix for this issue and this should soon be available in beta if you would like to beta test the fix. The cause was we were clearing build and version keys from shared preferences and the absence of these keys was being interpreted as a fresh install

fix: https://github.com/segmentio/analytics-android/pull/648

**Comment by aultimus** [comment] 2020-03-24 19:38
Hi, could you please try release 4.5.0-beta.2 which should address this issue. I am closing this issue, please re-open if the problem persists

https://github.com/segmentio/analytics-android/releases/tag/4.5.0-beta.2

**Closed** 2020-03-24 19:39 UTC
